language: python
matrix:
  exclude:
    - python: "3.3"
      env: REQ="django==1.4.10"
    - python: "2.7"
      env: REQ="django==1.6,<1.7 django-generic-m2m"
    - python: "2.7"
      env: REQ="django==1.6,<1.7 django-taggit django-generic-m2m"
    - python: "2.7"
      env: REQ="django==1.6,<1.7 django-taggit"
python:
  - "2.7"
  - "3.3"
env:
  matrix:
    - REQ="django>=1.4,<1.5"
    - REQ="django>=1.5,<1.6"
    - REQ="django>=1.6,<1.7"
    - REQ="django==1.6,<1.7 django-generic-m2m"
    - REQ="django==1.6,<1.7 django-taggit django-generic-m2m"
    - REQ="django==1.6,<1.7 django-taggit"
install:
  - pip install "$REQ"
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -r test_project/requirements.txt
  - pip install -r test_project/test_requirements.txt
  - pip install -e . --use-mirrors
  - pip install selenium==2.37.2
  - pip freeze
before_script:
  - "pep8 --exclude=tests,migrations --ignore=E124,E128 autocomplete_light"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python setup.py test
notifications:
  irc: 
    channels: 
      - "irc.freenode.org#yourlabs"
    template:
      - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
