sudo: false
language: python
matrix:
  allow_failures:
    - python: "3.4"
      env: TESTS_SKIP_LIVESERVER=1 REQ="-e git+https://github.com/django/django.git@master#egg=django django-taggit django-generic-m2m"
    - python: "2.7"
      env: TESTS_SKIP_LIVESERVER=1 REQ="-e git+https://github.com/django/django.git@master#egg=django django-taggit django-generic-m2m"
  exclude:
    # Python 3 is not supported with Django < 1.5.
    - python: "3.4"
      env: TESTS_SKIP_LIVESERVER=1 REQ="django<1.5 django-taggit django-generic-m2m"
    # Skip specific / single combinations for Python 2.
    - python: "2.7"
      env: REQ="django<1.8"
    - python: "2.7"
      env: REQ="django<1.8 django-generic-m2m"
    - python: "2.7"
      env: REQ="django<1.8 django-taggit"
python:
  - "2.7"
  - "3.4"
env:
  global:
    # Create wheels (skips existing ones from the cached wheelhouse).
    - export PIP_FIND_LINKS=$PWD/wheelhouse/
  matrix:
    - TESTS_SKIP_LIVESERVER=1 REQ="django<1.5 django-taggit django-generic-m2m"
    - TESTS_SKIP_LIVESERVER=1 REQ="django<1.6 django-taggit django-generic-m2m"
    - TESTS_SKIP_LIVESERVER=1 REQ="django<1.7 django-taggit django-generic-m2m"
    # Current stable Django.
    - TESTS_SKIP_LIVESERVER=1 REQ="django<1.8"
    - REQ="django<1.8 django-taggit django-generic-m2m"
    - TESTS_SKIP_LIVESERVER=1 REQ="django<1.8 django-taggit django-generic-m2m"
    - TESTS_SKIP_LIVESERVER=1 REQ="django<1.8 django-generic-m2m"
    - TESTS_SKIP_LIVESERVER=1 REQ="django<1.8 django-taggit"
    # django-master.
    - TESTS_SKIP_LIVESERVER=1 REQ="-e git+https://github.com/django/django.git@master#egg=django django-taggit django-generic-m2m"

    - REQ="pep8"
install:
  - pip install -U pip

  # NOTE: Django 1.4 wheel is broken; skip it (https://github.com/django/django/pull/2438).
  - if [[ $REQ != "django<1.5 django-taggit django-generic-m2m" ]]; then pip wheel $REQ; fi
  - pip wheel pep8 coveralls
  - pip wheel -r test_project/test_requirements.txt

  # Install from wheelhouse.
  # NOTE: Django 1.4 wheel is broken; skip it (https://github.com/django/django/pull/2438).
  - if [[ $REQ == "django<1.5 django-taggit django-generic-m2m" ]]; then pip install $REQ; fi
  - export PIP_NO_INDEX=1
  - pip install $REQ
  - pip install -r test_project/test_requirements.txt
  - pip install -e .
  - pip freeze
before_script:
  - which pep8 || psql -c 'create database autocomplete_light_test;' -U postgres
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - RUN_TESTS="test_project/manage.py test --traceback autocomplete_light --settings=test_project.settings_postgres"
  # Run tests either with or without coverage (being installed).
  - command -v coveralls && RUN_TESTS="coverage run --source=autocomplete_light $RUN_TESTS" || true
  # Run pep8 or the tests.
  - which pep8 && { pep8 --exclude=example_apps,tests,migrations --ignore=E124,E128 autocomplete_light; return $?; } || travis_retry $RUN_TESTS
after_success:
  - command -v coveralls && { coveralls; return $?; } || true
notifications:
  irc:
    channels:
      - "irc.freenode.org#yourlabs"
    template:
      - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"

# Persistent cache across builds (http://docs.travis-ci.com/user/caching/).
cache:
  directories:
    $PWD/wheelhouse/
